### ISSUE TITLE
Uncaught TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': The provided ...

### ISSUE THREAD

**Issue by garrettgu10** [AlynxZhou/atom-code-music#1]
1. Trigger the plugin.

**Atom**: 1.18.0-beta2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.2
**Thrown From**: [atom-code-music](https://github.com/AlynxZhou/atom-code-music) package 2.3.3

### Stack Trace

Uncaught TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': The provided value is not of type 'AudioBuffer'.

```
At /Users/garrettgu/.atom/packages/atom-code-music/libs/atom-code-music.coffee:99

TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceNode': The provided value is not of type 'AudioBuffer'.
    at TypeError (native)
    at AtomCodeMusic.noteOn (/packages/atom-code-music/libs/atom-code-music.coffee:99:11)
    at /packages/atom-code-music/libs/atom-code-music.coffee:1:1)
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-code-music 2.3.3 
atom-material-syntax 1.0.6 
atom-typescript 11.0.3 
autocomplete-java 1.2.7 
busy-signal 1.4.1 
color-picker 2.2.5 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.6.0 
nyancat 0.14.0 
platformio-ide-terminal 2.5.1 
remote-sync 4.1.5 
vim-mode-plus 0.93.0 
```

**Comment by AlynxZhou** [comment]
You mean just toggle and show this? Every time?

**Comment by AlynxZhou** [comment]
I think I fixed the bug in the newest version, can you try the new one? Sorry for answering after so long time.
